/** GeoNames English city → Chinese. Used so country drill-down stays in one language. */
const CITY_ZH = {
  Anking: "安庆",
  Anshan: "鞍山",
  Aral: "阿拉尔",
  Baoding: "保定",
  Baotou: "包头",
  Beijing: "北京",
  Bengbu: "蚌埠",
  Changchun: "长春",
  Changsha: "长沙",
  Changshu: "常熟",
  Changzhou: "常州",
  Chengdu: "成都",
  Chongqing: "重庆",
  Chuzhou: "滁州",
  Dali: "大理",
  Dalian: "大连",
  Daqing: "大庆",
  Dongguan: "东莞",
  Foshan: "佛山",
  Fushun: "抚顺",
  Fuxin: "阜新",
  Fuzhou: "福州",
  Ganzhou: "赣州",
  Guangzhou: "广州",
  Guilin: "桂林",
  Guiyang: "贵阳",
  Haikou: "海口",
  Haizhou: "海州",
  Handan: "邯郸",
  Hangzhou: "杭州",
  Harbin: "哈尔滨",
  Hefei: "合肥",
  Hengyang: "衡阳",
  Hohhot: "呼和浩特",
  "Huai'an": "淮安",
  Huainan: "淮南",
  Huangshi: "黄石",
  Huizhou: "惠州",
  Huzhou: "湖州",
  Jiangmen: "江门",
  Jiangning: "江宁",
  Jiaozuo: "焦作",
  Jiaxing: "嘉兴",
  "Jilin City": "吉林市",
  Jinan: "济南",
  Jingzhou: "荆州",
  Jinhua: "金华",
  Jinzhou: "锦州",
  Kaifeng: "开封",
  Kunming: "昆明",
  Kunshan: "昆山",
  Langfang: "廊坊",
  Lanzhou: "兰州",
  Lhasa: "拉萨",
  Liaocheng: "聊城",
  Linyi: "临沂",
  "Lin’an Shi": "临安",
  Liuzhou: "柳州",
  Luocheng: "罗城",
  Luoyang: "洛阳",
  "Ma'anshan City": "马鞍山",
  Maoming: "茂名",
  Mianyang: "绵阳",
  Nanchang: "南昌",
  Nanchong: "南充",
  Nanjing: "南京",
  Nanning: "南宁",
  Nantong: "南通",
  Nanyang: "南阳",
  Ningbo: "宁波",
  Qingdao: "青岛",
  Qinhuangdao: "秦皇岛",
  Qinzhou: "钦州",
  Qiqihar: "齐齐哈尔",
  Qufu: "曲阜",
  Shanghai: "上海",
  Shantou: "汕头",
  Shanxi: "山西",
  Shaoxing: "绍兴",
  Shenyang: "沈阳",
  Shenzhen: "深圳",
  Shihezi: "石河子",
  Shijiazhuang: "石家庄",
  Shiyan: "十堰",
  Suzhou: "苏州",
  Taiyuan: "太原",
  Taizhou: "泰州",
  "Tai’an": "泰安",
  Tangshan: "唐山",
  Tianjin: "天津",
  Tongshan: "铜山",
  Weifang: "潍坊",
  Wenzhou: "温州",
  Wuhan: "武汉",
  Wuhu: "芜湖",
  Wuxi: "无锡",
  "Xi'an": "西安",
  Xiamen: "厦门",
  Xiangfan: "襄阳",
  Xiangtan: "湘潭",
  Xiaodian: "小店",
  Xining: "西宁",
  Xinxiang: "新乡",
  Xinyang: "信阳",
  Xuzhou: "徐州",
  "Ya'an": "雅安",
  Yancheng: "盐城",
  Yangling: "杨凌",
  Yangpu: "洋浦",
  Yangzhou: "扬州",
  Yanji: "延吉",
  Yantai: "烟台",
  Yibin: "宜宾",
  Yichang: "宜昌",
  Yinchuan: "银川",
  Yiyang: "益阳",
  Yueyang: "岳阳",
  Zaozhuang: "枣庄",
  Zhangjiajie: "张家界",
  Zhangzhou: "漳州",
  Zhanjiang: "湛江",
  Zhengzhou: "郑州",
  Zhenjiang: "镇江",
  Zhoushan: "舟山",
  Zhuhai: "珠海",
  Zhuzhou: "株洲",
  Zibo: "淄博",
  Zigong: "自贡",
  Zunyi: "遵义",
  Ürümqi: "乌鲁木齐",
  Hong: "香港",
  "Hong Kong": "香港",
  Macau: "澳门",
  Macao: "澳门",
  Taipei: "台北",
  Taichung: "台中",
  Tainan: "台南",
  Kaohsiung: "高雄",
  Hsinchu: "新竹",
};

const UNI_ZH = {
  "grid.411485.d": "中国计量大学",
  "grid.411292.d": "成都大学",
  "grid.411431.2": "湖南工业大学",
  "grid.413242.2": "武汉纺织大学",
  "grid.412557.0": "沈阳农业大学",
  "grid.460017.4": "山东交通学院",
  "grid.460132.2": "西京学院",
  "grid.411870.b": "嘉兴大学",
  "grid.412064.5": "黑龙江八一农垦大学",
  "grid.411679.c": "汕头大学医学院",
  "grid.412562.6": "沈阳大学",
  "grid.503006.0": "河南科技学院",
  "grid.460151.7": "武汉商学院",
  "grid.412561.5": "沈阳药科大学",
  "grid.411671.4": "滁州学院",
  "grid.440665.5": "长春中医药大学",
  "grid.413073.2": "浙江树人大学",
  "grid.460162.7": "枣庄学院",
  "grid.413041.3": "宜宾学院",
  "grid.412068.9": "黑龙江中医药大学",
  "grid.459818.9": "北华航天工业学院",
};

export function cityName(city, locale) {
  if (!city) return "";
  if (locale === "zh") return CITY_ZH[city] || "";
  return city;
}

export function uniName(row, geo, locale) {
  if (locale === "zh") {
    return geo?.zh || UNI_ZH[row.org_id] || row.org_name_zh || row.org_name;
  }
  return row.org_name || geo?.zh || "";
}
